### ISSUE TITLE
Flat Cam crashes when importing Excellon file using inches

### ISSUE THREAD

**Issue by Diego-Sena-Boulder** [Jbsco/PCB_MFG#7]
When using the Flat Cam, you can not load an Excellon file when exported using inches.

**Comment by Jbsco** [comment]
Made Readme note of selecting millimeters in commit [1ddb891](https://github.com/Jbsco/PCB_MFG/commit/1ddb891103de92d94346e23f135f9d902ab4144c). This appears to be a bug in some installations of FlatCAM - see possibly related [Denvi/FlatCAM:#3](https://github.com/Denvi/FlatCAM/issues/3). Their issue tracker shows some users have problems with Excellon imports, so this may change with updates in the software.
